login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

home:
    path: /
    controller: App\Controller\DefaultController::index

register:
    path: /register
    controller: App\Controller\RegistrationController::register
